INTERNAL_API_PREFIX = "/internal"
HEADER_INTERNAL_TOKEN = "X-Internal-Token"
HEADER_TRACE_ID = "X-Trace-Id"

SUCCESS_CODE = "OK"
ERROR_VALIDATION = "VALIDATION_ERROR"
ERROR_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_INTERNAL = "INTERNAL_SERVER_ERROR"
