import { Eye, Users, UserPlus, Activity, Plus, Bug, Star } from "lucide-react";
import ds from "./designTokens";

/* ═══════════════════════════════════════════════
   목업 데이터 — 백엔드 연결 시 API 호출로 교체
   ═══════════════════════════════════════════════ */
const DATA = {
  kpi: [
    {
      id: "total",
      label: "전체 이벤트",
      current: 7265,
      previous: 8163,
      icon: Eye,
      color: ds.brand,
      bg: ds.brandSoft,
    },
    {
      id: "visit",
      label: "방문자 수",
      current: 3671,
      previous: 3672,
      icon: Users,
      color: ds.green,
      bg: ds.greenSoft,
    },
    {
      id: "new",
      label: "신규 참여자",
      current: 156,
      previous: 135,
      icon: UserPlus,
      color: ds.amber,
      bg: ds.amberSoft,
    },
    {
      id: "active",
      label: "활성 사용자",
      current: 2318,
      previous: 2185,
      icon: Activity,
      color: ds.violet,
      bg: ds.violetSoft,
    },
  ],

  userTrend: {
    thisYear: [
      { m: "1월", v: 8000 },
      { m: "2월", v: 15000 },
      { m: "3월", v: 12000 },
      { m: "4월", v: 18000 },
      { m: "5월", v: 22000 },
      { m: "6월", v: 19000 },
      { m: "7월", v: 25000 },
    ],
    lastYear: [
      { m: "1월", v: 5000 },
      { m: "2월", v: 9000 },
      { m: "3월", v: 11000 },
      { m: "4월", v: 8000 },
      { m: "5월", v: 14000 },
      { m: "6월", v: 16000 },
      { m: "7월", v: 18000 },
    ],
  },

  trafficSite: [
    { name: "Google", value: 40, color: ds.brand },
    { name: "YouTube", value: 25, color: ds.red },
    { name: "Instagram", value: 18, color: ds.violet },
    { name: "Pinterest", value: 10, color: ds.amber },
    { name: "네이버", value: 7, color: ds.green },
  ],

  trafficDevice: [
    { d: "1월", mobile: 12000, desktop: 18000, tablet: 5000 },
    { d: "2월", mobile: 15000, desktop: 20000, tablet: 6000 },
    { d: "3월", mobile: 18000, desktop: 22000, tablet: 7000 },
    { d: "4월", mobile: 22000, desktop: 19000, tablet: 8000 },
    { d: "5월", mobile: 25000, desktop: 24000, tablet: 6500 },
    { d: "6월", mobile: 20000, desktop: 21000, tablet: 7500 },
  ],

  locationTraffic: [
    { name: "서울", pct: 38.6, color: ds.brand },
    { name: "경기", pct: 22.5, color: ds.sky },
    { name: "부산", pct: 18.8, color: ds.violet },
    { name: "기타", pct: 20.1, color: ds.ink4 },
  ],

  notifications: [
    {
      msg: "신규 행사가 등록되었습니다.",
      time: "방금",
      icon: Plus,
      color: ds.green,
    },
    {
      msg: "새로운 사용자가 가입했습니다.",
      time: "5분 전",
      icon: UserPlus,
      color: ds.brand,
    },
    {
      msg: "버그 리포트가 수정되었습니다.",
      time: "12시간 전",
      icon: Bug,
      color: ds.amber,
    },
    {
      msg: "행사 구독자가 추가되었습니다.",
      time: "오늘 11:56",
      icon: Star,
      color: ds.violet,
    },
  ],

  activities: [
    { msg: "스타일 변경 완료", detail: "방금 전", color: ds.violet },
    { msg: "새 버전 배포", detail: "59분 전", color: ds.brand },
    { msg: "버그 리포트 제출", detail: "12시간 전", color: ds.amber },
    { msg: "Page A 데이터 수정", detail: "오늘 11:59", color: ds.green },
    { msg: "Project X 페이지 삭제", detail: "2월 2일", color: ds.red },
  ],

  contacts: [
    { name: "남광우", role: "푸푸 대표" },
    { name: "배재혁", role: "푸푸 대표" },
    { name: "정요한", role: "푸푸 대표" },
    { name: "김기정", role: "퇴근할게요" },
  ],

  congestion: [
    { zone: "메인 스테이지", pct: 92 },
    { zone: "체험존 A", pct: 68 },
    { zone: "체험존 B", pct: 45 },
    { zone: "포토 부스", pct: 81 },
    { zone: "휴식 공간", pct: 23 },
  ],

  zones: [
    { name: "반려견 놀이터", cur: 234, max: 300 },
    { name: "건강 체크존", cur: 156, max: 200 },
    { name: "포토 부스", cur: 189, max: 250 },
    { name: "훈련 클래스", cur: 98, max: 120 },
  ],

  contests: [
    { name: "애견 장기자랑", teams: 48, votes: 1240, live: true },
    { name: "베스트 스타일", teams: 32, votes: 890, live: true },
    { name: "멍때리기 대회", teams: 56, votes: 2100, live: false },
  ],

  events: Array.from({ length: 10 }, (_, i) => ({
    id: `EV-${String(i + 1).padStart(3, "0")}`,
    name: [
      "반려견 페스티벌",
      "펫 박람회",
      "캠핑 데이",
      "웰니스 데이",
      "라이프 페어",
      "교감 클래스",
      "어질리티 대회",
      "멍스타그램 파티",
      "펫 마라톤",
      "독 쇼",
    ][i],
    date: [
      "2026.01.10 ~ 2026.01.12",
      "2026.02.14 ~ 2026.02.16",
      "2026.03.05 ~ 2026.03.07",
      "2026.01.20 ~ 2026.01.22",
      "2026.02.28 ~ 2026.03.01",
      "2026.03.15 ~ 2026.03.16",
      "2026.01.25 ~ 2026.01.27",
      "2026.02.08 ~ 2026.02.09",
      "2026.03.20 ~ 2026.03.22",
      "2026.01.30 ~ 2026.02.01",
    ][i],
    location: [
      "올림픽 공원",
      "코엑스",
      "한강공원",
      "일산 킨텍스",
      "부산 벡스코",
      "세종문화회관",
      "잠실운동장",
      "서울숲",
      "여의도공원",
      "인천 송도",
    ][i],
    status: ["active", "pending", "ended"][i % 3],
    participants: [234, 156, 89, 312, 178, 95, 421, 67, 253, 144][i],
  })),

  programs: [
    {
      id: "PG-001",
      name: "기본 훈련 코스",
      category: "교육",
      sessions: 12,
      status: "active",
      enrolled: 48,
    },
    {
      id: "PG-002",
      name: "어질리티 입문",
      category: "체험",
      sessions: 8,
      status: "active",
      enrolled: 32,
    },
    {
      id: "PG-003",
      name: "반려견 영양학",
      category: "교육",
      sessions: 6,
      status: "pending",
      enrolled: 15,
    },
    {
      id: "PG-004",
      name: "펫 포토 클래스",
      category: "문화",
      sessions: 4,
      status: "active",
      enrolled: 56,
    },
    {
      id: "PG-005",
      name: "도그 요가",
      category: "체험",
      sessions: 10,
      status: "ended",
      enrolled: 72,
    },
    {
      id: "PG-006",
      name: "응급처치 교육",
      category: "교육",
      sessions: 3,
      status: "pending",
      enrolled: 20,
    },
  ],

  boards: [
    {
      id: 1,
      title: "2월 정기 행사 안내",
      author: "김관리",
      date: "2026.02.20",
      views: 234,
      pinned: true,
      answer:
        "2월 정기 행사는 2/28 토요일 오후 2시에 킨텍스 제1전시장에서 진행됩니다. 사전 등록을 권장드립니다.",
      answerDate: "2026.02.21",
    },
    {
      id: 2,
      title: "부스 배치 변경 공지",
      author: "박준호",
      date: "2026.02.18",
      views: 189,
      pinned: true,
    },
    {
      id: 3,
      title: "신규 파트너사 소개",
      author: "이서연",
      date: "2026.02.15",
      views: 156,
      pinned: false,
    },
    {
      id: 4,
      title: "시스템 점검 안내 (2/25)",
      author: "최민수",
      date: "2026.02.14",
      views: 312,
      pinned: false,
    },
    {
      id: 5,
      title: "이벤트 참가 규정 변경",
      author: "김관리",
      date: "2026.02.10",
      views: 98,
      pinned: false,
    },
  ],

  reviews: [
    {
      id: 1,
      title: "봄 페스티벌 정말 최고였어요!",
      author: "몽이맘",
      event: "2026 봄 반려동물 페스티벌",
      rating: 5,
      date: "2026.02.18",
      views: 312,
      content: "강아지와 함께 즐거운 시간 보냈습니다. 포토존도 너무 예뻤어요!",
    },
    {
      id: 2,
      title: "체험존 프로그램이 알찼어요",
      author: "코코아빠",
      event: "2026 봄 반려동물 페스티벌",
      rating: 4,
      date: "2026.02.16",
      views: 245,
      content: "다양한 체험 프로그램이 있어서 반려견과 함께하기 좋았습니다.",
    },
    {
      id: 3,
      title: "주차 안내가 아쉬웠습니다",
      author: "루이네",
      event: "겨울 캠핑 행사",
      rating: 3,
      date: "2026.02.14",
      views: 189,
      content: "행사 자체는 좋았지만 주차 안내가 부족해서 시간이 걸렸어요.",
    },
    {
      id: 4,
      title: "매년 참가하고 싶은 행사!",
      author: "초코러버",
      event: "2026 봄 반려동물 페스티벌",
      rating: 5,
      date: "2026.02.12",
      views: 421,
      content:
        "우리 초코가 너무 좋아했어요. 특히 간식 시식 코너가 인기 많았습니다.",
    },
    {
      id: 5,
      title: "강연 프로그램 퀄리티 높았습니다",
      author: "뽀식이",
      event: "2026 봄 반려동물 페스티벌",
      rating: 4,
      date: "2026.02.10",
      views: 167,
      content: "수의사 강연이 실질적으로 도움이 많이 되었어요.",
    },
    {
      id: 6,
      title: "반려견 건강검진 무료라 좋았어요",
      author: "솜이네",
      event: "겨울 캠핑 행사",
      rating: 5,
      date: "2026.02.08",
      views: 298,
      content: "건강검진 코너에서 무료로 체크해주셔서 감사했습니다.",
    },
  ],

  qna: [
    {
      id: 1,
      title: "다음 행사 일정이 언제인가요?",
      author: "김민준",
      date: "2026.02.22",
      views: 156,
      status: "답변완료",
      answer: "3월 중순 예정입니다. 공지사항을 확인해주세요.",
    },
    {
      id: 2,
      title: "반려동물 동반 입장 시 주의사항",
      author: "이하은",
      date: "2026.02.20",
      views: 234,
      status: "답변완료",
      answer: "목줄 착용 필수이며, 대형견은 입마개를 준비해주세요.",
    },
    {
      id: 3,
      title: "주차장 사전 예약 가능한가요?",
      author: "박서준",
      date: "2026.02.18",
      views: 89,
      status: "대기중",
      answer: "",
    },
    {
      id: 4,
      title: "환불 규정 문의드립니다",
      author: "최예린",
      date: "2026.02.16",
      views: 178,
      status: "답변완료",
      answer: "행사 3일 전까지 전액 환불 가능합니다.",
    },
    {
      id: 5,
      title: "포토존 예약은 어떻게 하나요?",
      author: "정우진",
      date: "2026.02.14",
      views: 145,
      status: "대기중",
      answer: "",
    },
    {
      id: 6,
      title: "음식 반입 가능 여부",
      author: "한소율",
      date: "2026.02.12",
      views: 203,
      status: "답변완료",
      answer: "외부 음식 반입은 제한되며, 행사장 내 푸드코트를 이용해주세요.",
    },
    {
      id: 7,
      title: "단체 할인 적용되나요?",
      author: "윤지호",
      date: "2026.02.10",
      views: 92,
      status: "대기중",
      answer: "",
    },
  ],

  forums: [
    {
      id: 1,
      title: "2026 신년 반려견 페스티벌",
      date: "2026.01.15",
      participants: 1240,
      posts: 356,
      status: "archived",
    },
    {
      id: 2,
      title: "겨울 캠핑 행사 후기",
      date: "2026.01.28",
      participants: 890,
      posts: 234,
      status: "archived",
    },
    {
      id: 3,
      title: "2025 연말 어워드",
      date: "2025.12.20",
      participants: 2100,
      posts: 567,
      status: "archived",
    },
    {
      id: 4,
      title: "가을 운동회 포럼",
      date: "2025.10.15",
      participants: 780,
      posts: 198,
      status: "archived",
    },
  ],

  notices: [
    {
      id: 1,
      title: "pupoo 플랫폼 v2.5 업데이트 안내",
      date: "2026.02.22",
      category: "시스템",
      important: true,
    },
    {
      id: 2,
      title: "개인정보 처리방침 변경 안내",
      date: "2026.02.20",
      category: "정책",
      important: true,
    },
    {
      id: 3,
      title: "3월 정기점검 일정 안내",
      date: "2026.02.18",
      category: "시스템",
      important: false,
    },
    {
      id: 4,
      title: "신규 기능: 실시간 대시보드",
      date: "2026.02.15",
      category: "기능",
      important: false,
    },
    {
      id: 5,
      title: "파트너 API 연동 가이드",
      date: "2026.02.10",
      category: "기능",
      important: false,
    },
  ],

  zoneManage: [
    {
      id: "ZN-001",
      name: "반려견 놀이터",
      type: "체험",
      capacity: 300,
      operator: "김태희",
      date: "2026.01.15",
      status: "active",
      description: "대형견/소형견 분리 운영",
    },
    {
      id: "ZN-002",
      name: "건강 체크존",
      type: "의료",
      capacity: 200,
      operator: "이수의",
      date: "2026.01.18",
      status: "active",
      description: "무료 건강검진 및 상담",
    },
    {
      id: "ZN-003",
      name: "포토 부스",
      type: "포토",
      capacity: 150,
      operator: "박사진",
      date: "2026.01.20",
      status: "active",
      description: "전문 포토그래퍼 상주",
    },
    {
      id: "ZN-004",
      name: "훈련 클래스",
      type: "체험",
      capacity: 80,
      operator: "최훈련",
      date: "2026.02.01",
      status: "pending",
      description: "기본 복종훈련 체험",
    },
    {
      id: "ZN-005",
      name: "펫 푸드코트",
      type: "푸드",
      capacity: 250,
      operator: "정요리",
      date: "2026.02.05",
      status: "active",
      description: "반려견 간식 시식 코너",
    },
    {
      id: "ZN-006",
      name: "공연 무대",
      type: "공연",
      capacity: 500,
      operator: "한무대",
      date: "2026.02.10",
      status: "ended",
      description: "메인 스테이지 공연장",
    },
  ],

  contestManage: [
    {
      id: "CT-001",
      name: "애견 장기자랑",
      category: "재주",
      teams: 48,
      votes: 1240,
      prize: "100만원",
      date: "2026.03.15",
      status: "active",
      description: "반려견 장기자랑 대회",
    },
    {
      id: "CT-002",
      name: "베스트 스타일",
      category: "패션",
      teams: 32,
      votes: 890,
      prize: "50만원",
      date: "2026.03.16",
      status: "active",
      description: "반려견 패션쇼",
    },
    {
      id: "CT-003",
      name: "멍때리기 대회",
      category: "재주",
      teams: 56,
      votes: 2100,
      prize: "30만원",
      date: "2026.03.14",
      status: "ended",
      description: "가장 오래 멍때리기",
    },
    {
      id: "CT-004",
      name: "어질리티 챔피언십",
      category: "스포츠",
      teams: 24,
      votes: 560,
      prize: "200만원",
      date: "2026.03.20",
      status: "pending",
      description: "장애물 코스 경주",
    },
    {
      id: "CT-005",
      name: "포토제닉 콘테스트",
      category: "사진",
      teams: 120,
      votes: 3400,
      prize: "80만원",
      date: "2026.03.18",
      status: "active",
      description: "가장 포토제닉한 반려견",
    },
  ],

  sessionManage: [
    {
      id: "SS-001",
      name: "반려견 행동학 기초",
      speaker: "김동물 교수",
      date: "2026.03.15",
      time: "10:00",
      duration: 60,
      location: "세미나실 A",
      enrolled: 45,
      capacity: 50,
      status: "active",
      description: "반려견 행동 이해하기",
    },
    {
      id: "SS-002",
      name: "펫 영양 세미나",
      speaker: "이영양 박사",
      date: "2026.03.15",
      time: "13:00",
      duration: 90,
      location: "세미나실 B",
      enrolled: 38,
      capacity: 40,
      status: "active",
      description: "올바른 사료 선택법",
    },
    {
      id: "SS-003",
      name: "응급처치 워크숍",
      speaker: "박수의 원장",
      date: "2026.03.16",
      time: "11:00",
      duration: 120,
      location: "실습실",
      enrolled: 28,
      capacity: 30,
      status: "pending",
      description: "반려견 응급상황 대처법",
    },
    {
      id: "SS-004",
      name: "어질리티 트레이닝",
      speaker: "최훈련사",
      date: "2026.03.16",
      time: "15:00",
      duration: 90,
      location: "야외 운동장",
      enrolled: 20,
      capacity: 25,
      status: "active",
      description: "기초 어질리티 훈련법",
    },
    {
      id: "SS-005",
      name: "반려동물 법률 Q&A",
      speaker: "정변호사",
      date: "2026.03.17",
      time: "14:00",
      duration: 60,
      location: "세미나실 A",
      enrolled: 50,
      capacity: 50,
      status: "ended",
      description: "반려동물 관련 법률 상담",
    },
  ],

  /* ── 지난 행사 관련 ── */
  pastEvents: [
    {
      id: "PE-001",
      name: "2025 가을 반려견 운동회",
      date: "2025.10.12",
      location: "올림픽 공원",
      participants: 1240,
      capacity: 1500,
      zoneUsage: 82,
      eventRate: 74,
      avgCongestion: 68,
    },
    {
      id: "PE-002",
      name: "2025 겨울 펫 박람회",
      date: "2025.12.20",
      location: "코엑스",
      participants: 2100,
      capacity: 2500,
      zoneUsage: 91,
      eventRate: 85,
      avgCongestion: 78,
    },
    {
      id: "PE-003",
      name: "2025 크리스마스 캠핑",
      date: "2025.12.24",
      location: "한강공원",
      participants: 890,
      capacity: 1000,
      zoneUsage: 76,
      eventRate: 69,
      avgCongestion: 55,
    },
    {
      id: "PE-004",
      name: "2026 신년 페스티벌",
      date: "2026.01.15",
      location: "일산 킨텍스",
      participants: 1560,
      capacity: 2000,
      zoneUsage: 88,
      eventRate: 79,
      avgCongestion: 72,
    },
    {
      id: "PE-005",
      name: "2026 설날 특별 행사",
      date: "2026.01.29",
      location: "세종문화회관",
      participants: 780,
      capacity: 1000,
      zoneUsage: 65,
      eventRate: 58,
      avgCongestion: 45,
    },
  ],

  pastHourlyCongestion: [
    { time: "09시", value: 15 },
    { time: "10시", value: 35 },
    { time: "11시", value: 62 },
    { time: "12시", value: 85 },
    { time: "13시", value: 78 },
    { time: "14시", value: 92 },
    { time: "15시", value: 88 },
    { time: "16시", value: 70 },
    { time: "17시", value: 45 },
    { time: "18시", value: 20 },
  ],

  /* ── 참가자 관련 ── */
  participants: [
    {
      id: "PT-001",
      name: "김민지",
      phone: "010-1234-5678",
      email: "minji@email.com",
      event: "반려견 페스티벌",
      petName: "몽이",
      petBreed: "말티즈",
      petAge: "3살",
      status: "approved",
      regDate: "2026.02.10",
      checkedIn: true,
      checkinTime: "09:32",
      payStatus: "paid",
      payMethod: "카드",
      amount: 35000,
    },
    {
      id: "PT-002",
      name: "이준호",
      phone: "010-2345-6789",
      email: "junho@email.com",
      event: "펫 박람회",
      petName: "초코",
      petBreed: "라브라도",
      petAge: "2살",
      status: "approved",
      regDate: "2026.02.11",
      checkedIn: true,
      checkinTime: "10:15",
      payStatus: "paid",
      payMethod: "카드",
      amount: 45000,
    },
    {
      id: "PT-003",
      name: "박서연",
      phone: "010-3456-7890",
      email: "seoyeon@email.com",
      event: "캠핑 데이",
      petName: "뽀미",
      petBreed: "포메라니안",
      petAge: "1살",
      status: "pending",
      regDate: "2026.02.12",
      checkedIn: false,
      checkinTime: null,
      payStatus: "unpaid",
      payMethod: "—",
      amount: 25000,
    },
    {
      id: "PT-004",
      name: "최동현",
      phone: "010-4567-8901",
      email: "donghyun@email.com",
      event: "반려견 페스티벌",
      petName: "바둑이",
      petBreed: "진돗개",
      petAge: "5살",
      status: "approved",
      regDate: "2026.02.08",
      checkedIn: true,
      checkinTime: "09:50",
      payStatus: "paid",
      payMethod: "계좌이체",
      amount: 35000,
    },
    {
      id: "PT-005",
      name: "정하은",
      phone: "010-5678-9012",
      email: "haeun@email.com",
      event: "웰니스 데이",
      petName: "솜이",
      petBreed: "비숑프리제",
      petAge: "2살",
      status: "approved",
      regDate: "2026.02.13",
      checkedIn: false,
      checkinTime: null,
      payStatus: "paid",
      payMethod: "카드",
      amount: 30000,
    },
    {
      id: "PT-006",
      name: "강태우",
      phone: "010-6789-0123",
      email: "taewoo@email.com",
      event: "어질리티 대회",
      petName: "맥스",
      petBreed: "보더콜리",
      petAge: "4살",
      status: "cancelled",
      regDate: "2026.02.09",
      checkedIn: false,
      checkinTime: null,
      payStatus: "refunded",
      payMethod: "카드",
      amount: 40000,
    },
    {
      id: "PT-007",
      name: "윤서현",
      phone: "010-7890-1234",
      email: "seohyun@email.com",
      event: "반려견 페스티벌",
      petName: "코코",
      petBreed: "푸들",
      petAge: "3살",
      status: "approved",
      regDate: "2026.02.14",
      checkedIn: true,
      checkinTime: "10:05",
      payStatus: "paid",
      payMethod: "카드",
      amount: 35000,
    },
    {
      id: "PT-008",
      name: "임재현",
      phone: "010-8901-2345",
      email: "jaehyun@email.com",
      event: "펫 박람회",
      petName: "루비",
      petBreed: "시츄",
      petAge: "6살",
      status: "pending",
      regDate: "2026.02.15",
      checkedIn: false,
      checkinTime: null,
      payStatus: "unpaid",
      payMethod: "—",
      amount: 45000,
    },
  ],

  checkins: [
    {
      id: "CK-001",
      participantId: "PT-001",
      name: "김민지",
      event: "반려견 페스티벌",
      method: "QR",
      time: "09:32",
      gate: "정문 A",
    },
    {
      id: "CK-002",
      participantId: "PT-002",
      name: "이준호",
      event: "펫 박람회",
      method: "수동",
      time: "10:15",
      gate: "정문 B",
    },
    {
      id: "CK-003",
      participantId: "PT-004",
      name: "최동현",
      event: "반려견 페스티벌",
      method: "QR",
      time: "09:50",
      gate: "정문 A",
    },
    {
      id: "CK-004",
      participantId: "PT-007",
      name: "윤서현",
      event: "반려견 페스티벌",
      method: "QR",
      time: "10:05",
      gate: "후문",
    },
  ],

  sessionParticipation: [
    {
      id: "SP-001",
      participant: "김민지",
      pet: "몽이 (말티즈)",
      session: "기본 훈련 코스",
      callTime: "11:00",
      startTime: "11:05",
      endTime: "11:55",
      result: "완료",
    },
    {
      id: "SP-002",
      participant: "이준호",
      pet: "초코 (라브라도)",
      session: "어질리티 입문",
      callTime: "13:00",
      startTime: "13:10",
      endTime: "14:00",
      result: "완료",
    },
    {
      id: "SP-003",
      participant: "최동현",
      pet: "바둑이 (진돗개)",
      session: "기본 훈련 코스",
      callTime: "11:00",
      startTime: "11:08",
      endTime: "11:55",
      result: "완료",
    },
    {
      id: "SP-004",
      participant: "윤서현",
      pet: "코코 (푸들)",
      session: "펫 포토 클래스",
      callTime: "14:00",
      startTime: "14:05",
      endTime: null,
      result: "진행중",
    },
    {
      id: "SP-005",
      participant: "정하은",
      pet: "솜이 (비숑프리제)",
      session: "도그 요가",
      callTime: "15:00",
      startTime: null,
      endTime: null,
      result: "대기",
    },
  ],

  alertHistory: [
    {
      id: "AL-001",
      title: "행사 당일 안내",
      content: "반려견 페스티벌이 내일 진행됩니다. 오전 9시까지 입장해주세요.",
      target: "전체",
      targetCount: 234,
      sentDate: "2026.02.14",
      status: "sent",
    },
    {
      id: "AL-002",
      title: "체크인 미완료 알림",
      content:
        "아직 체크인을 하지 않으셨습니다. 행사장에서 QR코드를 보여주세요.",
      target: "미체크인",
      targetCount: 56,
      sentDate: "2026.02.15",
      status: "sent",
    },
    {
      id: "AL-003",
      title: "결제 안내",
      content: "미결제 건이 있습니다. 확인 부탁드립니다.",
      target: "미결제",
      targetCount: 12,
      sentDate: null,
      status: "draft",
    },
    {
      id: "AL-004",
      title: "이벤트 종료 감사 인사",
      content: "참여해 주셔서 감사합니다. 다음 행사에서 만나요!",
      target: "체크인완료",
      targetCount: 178,
      sentDate: "2026.02.16",
      status: "sent",
    },
    {
      id: "AL-005",
      title: "설문조사 요청",
      content: "행사 만족도 설문에 참여해주세요.",
      target: "전체",
      targetCount: 234,
      sentDate: null,
      status: "draft",
    },
  ],

  participantStats: {
    totalRegistered: 1284,
    totalCheckedIn: 1089,
    checkinRate: 84.8,
    avgSatisfaction: 4.3,
    monthlyTrend: [
      { month: "9월", participants: 156 },
      { month: "10월", participants: 234 },
      { month: "11월", participants: 189 },
      { month: "12월", participants: 312 },
      { month: "1월", participants: 267 },
      { month: "2월", participants: 126 },
    ],
    byEvent: [
      { name: "반려견 페스티벌", registered: 234, checkedIn: 212, rate: 90.6 },
      { name: "펫 박람회", registered: 156, checkedIn: 132, rate: 84.6 },
      { name: "캠핑 데이", registered: 89, checkedIn: 71, rate: 79.8 },
      { name: "웰니스 데이", registered: 312, checkedIn: 245, rate: 78.5 },
      { name: "어질리티 대회", registered: 178, checkedIn: 162, rate: 91.0 },
    ],
  },

  gallery: [
    {
      id: "GL-001",
      tab: "참가자",
      title: "봄 페스티벌 후기",
      author: "몽이맘",
      pet: "몽이 (말티즈 3살)",
      date: "2026.02.14",
      photos: 2,
      likes: 47,
      views: 312,
      content:
        "드디어 다녀왔어요! 몽이가 너무 신나서 계속 뛰어다녔답니다 🐾 포토부스에서 찍은 사진이 너무 귀엽게 나왔어요",
      tags: ["봄페스티벌", "말티즈", "포토부스"],
      status: "active",
      thumbnail: "🐕",
    },
    {
      id: "GL-002",
      tab: "참가자",
      title: "솜이의 첫 행사",
      author: "솜이네",
      pet: "솜이 (포메라니안 1살)",
      date: "2026.02.13",
      photos: 3,
      likes: 89,
      views: 541,
      content:
        "솜이가 처음에는 무서워했는데 나중에는 친구도 사귀고 너무 잘 놀았어요 😊 내년에도 꼭 올게요!",
      tags: ["포메라니안", "솜이", "행복했어요"],
      status: "active",
      thumbnail: "🐶",
    },
    {
      id: "GL-003",
      tab: "참가자",
      title: "먹거리 존 추천",
      author: "뽀식이",
      pet: "뽀식 (비숑프리제 2살)",
      date: "2026.02.12",
      photos: 2,
      likes: 34,
      views: 227,
      content:
        "먹거리 존에서 강아지 케이크 사줬는데 순식간에 다 먹어버렸어요 😍 다음에는 두 개 사야할 것 같아요",
      tags: ["먹방", "비숑", "강아지케이크"],
      status: "active",
      thumbnail: "🐩",
    },
    {
      id: "GL-004",
      tab: "참가자",
      title: "건강검진 후기",
      author: "초코러버",
      pet: "초코 (라브라도 3살)",
      date: "2026.02.11",
      photos: 4,
      likes: 52,
      views: 389,
      content:
        "반려동물 건강검진 코너가 정말 유익했어요. 무료로 해주셨는데 담당 수의사 선생님이 너무 친절하셨어요.",
      tags: ["건강검진", "수의사", "라브라도"],
      status: "active",
      thumbnail: "🦮",
    },
    {
      id: "GL-005",
      tab: "현장",
      title: "2026 봄 반려동물 페스티벌 메인 행사장",
      author: "운영팀",
      pet: "",
      date: "2026.02.12",
      photos: 3,
      likes: 0,
      views: 0,
      content:
        "200여 마리의 강아지와 고양이가 함께한 봄 페스티벌 현장 스케치입니다.",
      tags: ["현장스케치"],
      status: "active",
      thumbnail: "🏟️",
    },
    {
      id: "GL-006",
      tab: "현장",
      title: "체험존 & 포토 부스 현장",
      author: "운영팀",
      pet: "",
      date: "2026.02.12",
      photos: 2,
      likes: 0,
      views: 0,
      content:
        "다양한 체험 프로그램과 포토 부스에서 즐거운 시간을 보낸 참가자들.",
      tags: ["현장스케치"],
      status: "active",
      thumbnail: "📸",
    },
    {
      id: "GL-007",
      tab: "현장",
      title: "인기 반려견 선발 시상식",
      author: "운영팀",
      pet: "",
      date: "2026.02.11",
      photos: 1,
      likes: 0,
      views: 0,
      content: "치열한 경쟁 끝에 최고 인기상을 수상한 반려견들의 빛나는 순간.",
      tags: ["현장스케치"],
      status: "active",
      thumbnail: "🏆",
    },
    {
      id: "GL-008",
      tab: "현장",
      title: "전문 강연 & 세션 현장",
      author: "운영팀",
      pet: "",
      date: "2026.02.10",
      photos: 4,
      likes: 0,
      views: 0,
      content: "수의사 및 반려동물 전문가들의 유익한 강연이 펼쳐진 세미나홀.",
      tags: ["현장스케치"],
      status: "active",
      thumbnail: "🎤",
    },
  ],
};

export default DATA;
