apiVersion: v1
kind: ConfigMap
metadata:
  name: pupoo-backend-config
  namespace: pupoo
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  AI_SERVICE_BASE_URL: "http://pupoo-ai:80"
  AI_MODERATION_BASE_URL: "http://pupoo-ai:80"
  STORAGE_MODE: "S3"
  STORAGE_S3_REGION: "ap-northeast-2"
  STORAGE_S3_KEY_PREFIX: "uploads"
  APP_STORAGE_CDN_BASE_URL: "https://cdn.pupoo.site"
  SPRING_DATASOURCE_URL: "jdbc:mysql://pupoo-rds.cluster-xxxxxxxx.ap-northeast-2.rds.amazonaws.com:3306/pupoodb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  APP_CORS_ALLOWED_ORIGIN_PATTERNS: "https://app.pupoo.com,https://admin.pupoo.com,https://pupoo.site,https://www.pupoo.site"
